### ISSUE TITLE
Get rid of CMFQuickInstallerTool dependency

### ISSUE THREAD

**Issue by mauritsvanrees** [collective/collective.revisionmanager#27]
Version 1.0.0 pulls in `Products.CMFQuickInstallerTool >= 3.0.9` for the install profile. See [`setup.py`](https://github.com/collective/collective.revisionmanager/blob/1.0.0/setup.py#L61). On Plone 6 you do not want this. For example, it breaks Plone upgrade:

```
Traceback (most recent call last):
  File "/Users/maurits/clients/minaraad-py3/src/Products.CMFPlone/Products/CMFPlone/MigrationTool.py", line 290, in upgrade
    step['step'].doStep(setup)
  File "/Users/maurits/shared-eggs/cp38/Products.GenericSetup-2.1.1-py3.8.egg/Products/GenericSetup/upgrade.py", line 168, in doStep
    self.handler(tool)
  File "/Users/maurits/clients/minaraad-py3/src/plone.app.upgrade/plone/app/upgrade/v60/alphas.py", line 11, in to60alpha1
    loadMigrationProfile(context, 'profile-plone.app.upgrade.v60:to60alpha1')
  File "/Users/maurits/clients/minaraad-py3/src/plone.app.upgrade/plone/app/upgrade/utils.py", line 203, in loadMigrationProfile
    context.runAllImportStepsFromProfile(profile, purge_old=False)
  File "/Users/maurits/shared-eggs/cp38/Products.GenericSetup-2.1.1-py3.8.egg/Products/GenericSetup/tool.py", line 399, in runAllImportStepsFromProfile
    result = self._runImportStepsFromContext(
  File "/Users/maurits/shared-eggs/cp38/Products.GenericSetup-2.1.1-py3.8.egg/Products/GenericSetup/tool.py", line 1468, in _runImportStepsFromContext
    event.notify(
  File "/Users/maurits/shared-eggs/cp38/zope.event-4.5.0-py3.8.egg/zope/event/__init__.py", line 32, in notify
    subscriber(event)
  File "/Users/maurits/shared-eggs/cp38/zope.component-4.6.2-py3.8.egg/zope/component/event.py", line 27, in dispatch
    component_subscribers(event, None)
  File "/Users/maurits/shared-eggs/cp38/zope.component-4.6.2-py3.8.egg/zope/component/_api.py", line 134, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/Users/maurits/shared-eggs/cp38/zope.interface-5.2.0-py3.8-macosx-10.15-x86_64.egg/zope/interface/registry.py", line 448, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/Users/maurits/shared-eggs/cp38/zope.interface-5.2.0-py3.8-macosx-10.15-x86_64.egg/zope/interface/adapter.py", line 619, in subscribers
    subscription(*objects)
  File "/Users/maurits/shared-eggs/cp38/Products.CMFQuickInstallerTool-4.0.4-py3.8.egg/Products/CMFQuickInstallerTool/events.py", line 49, in handleBeforeProfileImportEvent
    product = findProductForProfile(context, profile_id, qi)
  File "/Users/maurits/shared-eggs/cp38/Products.CMFQuickInstallerTool-4.0.4-py3.8.egg/Products/CMFQuickInstallerTool/events.py", line 18, in findProductForProfile
    request._cachedInstallableProducts = qi.listInstallableProducts(
AttributeError: 'QuickInstallerTool' object has no attribute 'listInstallableProducts'
```

The least invasive solution would be to drop this dependency, and instead require `Products.CMFPlone>=4.3.7`, because this version by default contains `Products.CMFQuickInstallerTool` 3.0.12.

**Comment by mauritsvanrees** [comment]
I have released `collective.revisionmanager 1.1.0` with this.
Seems to work in Plone 6 (pre alpha).
